Revert "Python 3: file() --> open() in yaml-highlight example (#236)"
This reverts commit a5f4329ac595d06da91d018195c33de9bc48e0f9.

Still not working with python3:
    % PYTHONPATH=$PWD/lib3 python3 examples/yaml-highlight/yaml_hl.py <.appveyor.yml
    Traceback (most recent call last):
      File "examples/yaml-highlight/yaml_hl.py", line 126, in <module>
        hl.highlight()
      File "examples/yaml-highlight/yaml_hl.py", line 66, in highlight
        if input.startswith(codecs.BOM_UTF16_LE):
    TypeError: startswith first arg must be str or a tuple of str, not bytes

and getting this warning in python2:
Exception AttributeError: "'NoneType' object has no attribute 'stdin'" in <bound method YAMLHighlight.__del__ of <__main__.YAMLHighlight instance at 0x7fb9b81a47a0>> ignored